### ISSUE TITLE
Operations module should only rely on raw np.ndarrays

### ISSUE THREAD

**Issue by RodrigoAlcala** [RodrigoAlcala/LacidMed#7]
Viendo de nuevo el codigo creo que seria de buena practica seguir el workflow de carga de imagenes y evitar leerlas de nuevo cuando se ejecutan operaciones.

La clase Operations te pide los directorios de input, cuando podria ser una clase sin inits a la que le cargues directamente N, ndarrays y hagas las operaciones sobre eso.

**Comment by Hactar-Santi** [comment]
Cambié todo a arrays
